### PR TITLE
add composer add namespace and change directory

### PR DESCRIPTION
**Pull request by qneyrat**
i add composer in your project for use in php framework like symfony.
Please fix email adress in composer.json file.
If you have question, i'm here !
Thx 👍

### CODE REVIEW

**Comment by MineTheCube** [comment]
I'm not sure about this.. 
Composer is a great and easy tool when you know how to use it, but MojangAPI class is meant to be a copy/paste code rather than a library.

What's bothering me is the namespace, I think too many people will just copy "MojangAPI::method()" and forgot about the namespace (maybe they even don't know what it is), then complain that it doesn't work.

**Comment by games647** [comment]
You could still add composer **and** make it copy-paste compatible. I think that's the best option.

>What's bothering me is the namespace, I think too many people will just copy "MojangAPI::method()" and forgot about the namespace (maybe they even don't know what it is), then complain that it doesn't work.

Just add a note that they should add a use statement too.

**Comment by qneyrat** [comment]
Everyone uses Composer 👍

**Comment by MineTheCube** [comment]
> Everyone uses Composer 👍

If only... It would make things a lot easier !

Well I may have a solution to allow both composer and simple copy/paste. I could put composer stuff in a `composer/` folder, and make another folder `standalone/` next to it where classes would be too but without namespace.

So composer would only load `composer/` classes, and for those who don't use it, I can link them `standalone/` folder.

The only downside is that I would end up with 2 `MojangApi` classes.

**Comment by games647** [comment]
Just use the same files. They would just have to make use of the "use"-statement.

**Comment by qneyrat** [comment]
Composer will not prevent you to use your static functions..  Just to use ALSO as a Vendor or Static. I finish soon my api for minecraft and mojang with more tools :)

**Pull request closed without merging**
